#!/usr/bin/env python3
from pathlib import Path

ROOT = Path.cwd()


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def write(rel: str, text: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def replace_once(rel: str, old: str, new: str) -> None:
    text = read(rel)
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{rel}: expected one occurrence, found {count}: {old[:120]!r}")
    write(rel, text.replace(old, new, 1))


write(
    "src/ts/src/request-contract.ts",
    '''/**
 * Runtime validation boundary for schemas generated by api-docs.
 *
 * Operation selection is deliberately split from validation: `resolve` receives
 * only method + pathname. Query values, headers, and the body clone are exposed
 * only after a method/path match, so the public API cannot use them as alternate
 * dispatch selectors.
 */
export type MaybePromise<T> = T | Promise<T>;

export interface RequestContractIssue {
  readonly path: string;
  readonly code: string;
  readonly message: string;
}

export interface RequestContractValidationInput {
  readonly method: string;
  readonly pathname: string;
  readonly pathTemplate: string;
  readonly pathParams: Readonly<Record<string, string>>;
  readonly query: readonly (readonly [string, string])[];
  readonly headers: readonly (readonly [string, string])[];
  /** A clone owned by the validator; consuming it never consumes the handler request. */
  readonly request: Request;
}

export interface RequestContractMatch {
  readonly pathTemplate: string;
  readonly pathParams?: Readonly<Record<string, string>>;
  validate(
    input: RequestContractValidationInput
  ): MaybePromise<readonly RequestContractIssue[]>;
}

export interface RequestContractValidator {
  /**
   * Resolve an operation from routing identity only. Deliberately no query,
   * headers, body, or request object is available at this stage.
   */
  resolve(method: string, pathname: string): MaybePromise<RequestContractMatch | undefined>;
}

export interface RequestContractFailure {
  readonly status: 400 | 404;
  readonly code: "unknown_operation" | "request_contract_validation_failed";
  readonly issues: readonly RequestContractIssue[];
}

function freezePairs(
  pairs: Iterable<readonly [string, string]>
): readonly (readonly [string, string])[] {
  return Object.freeze(
    Array.from(pairs, ([key, value]) => Object.freeze([key, value] as const))
  );
}

function freezePathParams(
  values: Readonly<Record<string, string>> | undefined
): Readonly<Record<string, string>> {
  return Object.freeze({ ...(values ?? {}) });
}

function normalizeIssues(
  issues: readonly RequestContractIssue[]
): readonly RequestContractIssue[] {
  if (!Array.isArray(issues)) {
    throw new TypeError("request contract validator must return an issue array");
  }
  return Object.freeze(
    issues.map((issue, index) => {
      if (
        !issue ||
        typeof issue.path !== "string" ||
        typeof issue.code !== "string" ||
        typeof issue.message !== "string"
      ) {
        throw new TypeError(`request contract issue ${index} is malformed`);
      }
      return Object.freeze({
        path: issue.path,
        code: issue.code,
        message: issue.message
      });
    })
  );
}

export async function checkRequestContract(
  validator: RequestContractValidator | undefined,
  request: Request,
  url: URL = new URL(request.url)
): Promise<RequestContractFailure | undefined> {
  if (!validator) return undefined;

  const method = request.method.toUpperCase();
  const pathname = url.pathname;
  const match = await validator.resolve(method, pathname);
  if (!match) {
    return Object.freeze({
      status: 404,
      code: "unknown_operation",
      issues: Object.freeze([
        Object.freeze({
          path: "/",
          code: "unknown_operation",
          message: "no request contract matched the HTTP method and pathname"
        })
      ])
    });
  }

  if (!match.pathTemplate.startsWith("/")) {
    throw new TypeError("request contract pathTemplate must begin with '/'");
  }

  const input: RequestContractValidationInput = Object.freeze({
    method,
    pathname,
    pathTemplate: match.pathTemplate,
    pathParams: freezePathParams(match.pathParams),
    query: freezePairs(url.searchParams.entries()),
    headers: freezePairs(request.headers.entries()),
    request: request.clone()
  });
  const issues = normalizeIssues(await match.validate(input));
  if (issues.length === 0) return undefined;

  return Object.freeze({
    status: 400,
    code: "request_contract_validation_failed",
    issues
  });
}
''',
)

replace_once(
    "src/ts/src/index.ts",
    '''import { currentContext, runWithContext } from "./context.js";
''',
    '''import { currentContext, runWithContext } from "./context.js";
import {
  checkRequestContract,
  type RequestContractValidator
} from "./request-contract.js";
''',
)
replace_once(
    "src/ts/src/index.ts",
    '''export { currentContext, runWithContext };
''',
    '''export { currentContext, runWithContext, checkRequestContract };
export type {
  RequestContractFailure,
  RequestContractIssue,
  RequestContractMatch,
  RequestContractValidationInput,
  RequestContractValidator
} from "./request-contract.js";
''',
)
replace_once(
    "src/ts/src/index.ts",
    '''  /** Optional audited sink; defaults to the bounded ores-otel reporter. */
  operationFailureReporter?: OperationFailureReporter;
''',
    '''  /** Optional audited sink; defaults to the bounded ores-otel reporter. */
  operationFailureReporter?: OperationFailureReporter;
  /**
   * Strict parsed-request contract boundary. Its resolver receives method +
   * pathname only; query/header/body values are validation-only inputs.
   */
  requestContractValidator?: RequestContractValidator;
''',
)
replace_once(
    "src/ts/src/index.ts",
    '''    if (dependencies.authorizeIp && !(await dependencies.authorizeIp(request, context))) return problem(403, "ip_policy_denied", "request source is not permitted");
    if (config.settings.rateLimit.enabled) {
''',
    '''    if (dependencies.authorizeIp && !(await dependencies.authorizeIp(request, context))) return problem(403, "ip_policy_denied", "request source is not permitted");

    const contractFailure = await checkRequestContract(
      dependencies.requestContractValidator,
      request,
      url
    );
    if (contractFailure) {
      const detail = contractFailure.code === "unknown_operation"
        ? "no request contract matched the HTTP method and pathname"
        : "request path, query, headers, or JSON payload failed contract validation";
      return problem(contractFailure.status, contractFailure.code, detail);
    }

    if (config.settings.rateLimit.enabled) {
''',
)

package = read("src/ts/package.json")
old = '''    "./operation": {
      "types": "./dist/operation.d.ts",
      "import": "./dist/operation.js"
    },
    "./otel": {
'''
new = '''    "./operation": {
      "types": "./dist/operation.d.ts",
      "import": "./dist/operation.js"
    },
    "./request-contract": {
      "types": "./dist/request-contract.d.ts",
      "import": "./dist/request-contract.js"
    },
    "./otel": {
'''
if package.count(old) != 1:
    raise SystemExit("src/ts/package.json operation export block not found")
write("src/ts/package.json", package.replace(old, new, 1))

write(
    "src/ts/test/request-contract-validation.test.mjs",
    '''import assert from "node:assert/strict";
import test from "node:test";

import {
  checkRequestContract,
  createMiddleware,
  currentContext,
  defaultConfig
} from "../dist/index.js";

function config() {
  const value = defaultConfig("request-contract-test");
  value.environment = "test";
  value.settings.rateLimit.enabled = false;
  value.settings.idempotency.enabled = false;
  value.settings.compression.enabled = false;
  value.settings.securityHeaders.enabled = false;
  return value;
}

function jsonRequest(url, body, headers = {}) {
  return new Request(url, {
    method: "POST",
    headers: { "content-type": "application/json", ...headers },
    body: JSON.stringify(body)
  });
}

test("resolver identity is method + pathname only and validator receives immutable surfaces", async () => {
  const resolved = [];
  const validated = [];
  const validator = {
    resolve(method, pathname, ...unexpected) {
      resolved.push([method, pathname, unexpected.length]);
      return {
        pathTemplate: "/v1/items/{id}",
        pathParams: { id: "42" },
        async validate(input) {
          assert.equal(Object.isFrozen(input), true);
          assert.equal(Object.isFrozen(input.pathParams), true);
          assert.equal(Object.isFrozen(input.query), true);
          assert.equal(Object.isFrozen(input.headers), true);
          assert.equal(Object.isFrozen(input.query[0]), true);
          assert.equal(Object.isFrozen(input.headers[0]), true);
          validated.push({
            method: input.method,
            pathname: input.pathname,
            pathTemplate: input.pathTemplate,
            pathParams: input.pathParams,
            query: input.query,
            headers: input.headers,
            body: await input.request.json()
          });
          return [];
        }
      };
    }
  };

  const middleware = createMiddleware(config(), { requestContractValidator: validator });
  const inputs = [
    jsonRequest("https://example.test/v1/items/42?view=full", { name: "alpha" }, { "x-client-version": "1" }),
    jsonRequest("https://example.test/v1/items/42?view=compact", { name: "beta" }, { "x-client-version": "2" })
  ];

  for (const request of inputs) {
    const response = await middleware(request, async (handlerRequest) => {
      const body = await handlerRequest.json();
      return Response.json({ body });
    });
    assert.equal(response.status, 200);
  }

  assert.deepEqual(resolved, [
    ["POST", "/v1/items/42", 0],
    ["POST", "/v1/items/42", 0]
  ]);
  assert.equal(validated[0].query[0][1], "full");
  assert.equal(validated[1].query[0][1], "compact");
  assert.equal(validated[0].headers.some(([name, value]) => name === "x-client-version" && value === "1"), true);
  assert.deepEqual(validated.map((entry) => entry.body.name), ["alpha", "beta"]);
  assert.equal(currentContext(), undefined);
});

test("invalid path/query/header/body surfaces fail before rate limiting, auth, and handler execution", async () => {
  let rateCalls = 0;
  let authCalls = 0;
  let handlerCalls = 0;
  const value = config();
  value.settings.rateLimit.enabled = true;

  const middleware = createMiddleware(value, {
    requestContractValidator: {
      resolve() {
        return {
          pathTemplate: "/v1/items/{id}",
          pathParams: { id: "not-a-uuid" },
          validate() {
            return [{ path: "/headers/x-client-version", code: "required", message: "header is required" }];
          }
        };
      }
    },
    rateLimiter: {
      async allow() {
        rateCalls += 1;
        return true;
      }
    },
    async authVerifier() {
      authCalls += 1;
      return { userId: "user-1" };
    }
  });

  const response = await middleware(
    jsonRequest("https://example.test/v1/items/not-a-uuid", { name: 7 }),
    async () => {
      handlerCalls += 1;
      return Response.json({ ok: true });
    }
  );

  assert.equal(response.status, 400);
  const body = await response.json();
  assert.equal(body.title, "request_contract_validation_failed");
  assert.equal(rateCalls, 0);
  assert.equal(authCalls, 0);
  assert.equal(handlerCalls, 0);
  assert.equal(currentContext(), undefined);
});

test("strict validator returns 404 when method + pathname have no declared operation", async () => {
  const middleware = createMiddleware(config(), {
    requestContractValidator: { resolve: () => undefined }
  });
  const response = await middleware(
    new Request("https://example.test/missing"),
    async () => Response.json({ unreachable: true })
  );
  assert.equal(response.status, 404);
  assert.equal((await response.json()).title, "unknown_operation");
});

test("validator issue arrays are runtime checked and malformed adapters fail closed", async () => {
  const request = new Request("https://example.test/v1/items/42");
  await assert.rejects(
    () => checkRequestContract(
      {
        resolve: () => ({
          pathTemplate: "/v1/items/{id}",
          validate: () => [{ path: 42, code: "bad", message: "bad" }]
        })
      },
      request
    ),
    /issue 0 is malformed/
  );
});
''',
)

write(
    "docs/request-contract-validation.md",
    '''# Request-contract validation boundary

`ores-middleware` can enforce the parsed HTTP contracts generated by
`ORESoftware/api-docs` before authentication or handler execution.

The boundary deliberately separates routing from validation:

```ts
interface RequestContractValidator {
  resolve(method: string, pathname: string): RequestContractMatch | undefined;
}
```

Only method and pathname are available during operation resolution. After the
match, its validator receives immutable snapshots of path parameters, repeated
query pairs, canonical header pairs, and a request clone for JSON-body parsing.
It may return validation issues, but it cannot return or replace a route.

This makes header-based and query-based routing structurally unavailable while
still supporting compile-time generated request types and Draft 2020-12 runtime
schemas.

## Typical adapter

At application startup, compile the `api-docs` schemas with the JSON Schema
validator selected by the service. Build a method/path matcher from generated
route metadata. Its `resolve` callback returns the already-compiled operation
validator and path parameters. Do not pass query parameters or headers into the
matcher.

At request time the middleware:

1. applies payload-size, content negotiation, TLS, forwarded-header, and IP checks;
2. resolves the request contract from normalized method + pathname;
3. validates path/query/header/body data from a cloned request;
4. rejects unknown operations with 404 and invalid request surfaces with 400;
5. runs rate limiting, authentication, telemetry, and the handler only after validation succeeds.

Validation failures intentionally use a generic public problem response. Detailed
schema paths remain available to the adapter for bounded internal telemetry and
must not include request bodies, credentials, cookies, or authorization values.

## Build and pre-deploy policy

Services should compile generated language clients, run `ridl check` and `ridl
drift`, validate positive and mutation fixtures against the generated per-route
schemas, and refuse promotion when TypeSpec and JSON Schema peer authorities
disagree. Runtime validation supplements those gates; it does not replace them.
''',
)

print("request-contract validation port applied")
