/**
 * Runtime validation boundary for schemas generated by api-docs.
 *
 * Operation selection is deliberately split from validation: `resolve` receives
 * only method + pathname. Query values, declared application headers, and body
 * readers are exposed only after a method/path match, so the public API cannot
 * use them as alternate dispatch selectors.
 */
export type MaybePromise<T> = T | Promise<T>;

const HTTP_HEADER_NAME_RE = /^[!#$%&'*+.^_`|~0-9a-z-]+$/;
const RUNTIME_OWNED_REQUEST_HEADERS = new Set([
  "authorization",
  "baggage",
  "connection",
  "content-encoding",
  "content-length",
  "content-type",
  "cookie",
  "forwarded",
  "host",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "set-cookie",
  "te",
  "traceparent",
  "tracestate",
  "trailer",
  "transfer-encoding",
  "upgrade",
  "x-forwarded-for",
  "x-forwarded-host",
  "x-forwarded-proto",
  "x-real-ip"
]);

export interface RequestContractIssue {
  readonly path: string;
  readonly code: string;
  readonly message: string;
}

/**
 * Isolated, repeatable readers over body clones. The validator cannot inspect
 * cookies, authorization, proxy metadata, or any other Request properties.
 */
export interface RequestContractBody {
  readonly present: boolean;
  json(): Promise<unknown>;
  text(): Promise<string>;
}

export interface RequestContractValidationInput {
  readonly method: string;
  readonly pathname: string;
  readonly pathTemplate: string;
  readonly pathParams: Readonly<Record<string, string>>;
  readonly query: readonly (readonly [string, string])[];
  /** Only names explicitly declared by the matched operation are projected. */
  readonly headers: readonly (readonly [string, string])[];
  readonly body: RequestContractBody;
}

export interface RequestContractMatch {
  readonly pathTemplate: string;
  readonly pathParams?: Readonly<Record<string, string>>;
  /**
   * Canonical lower-case, application-owned headers declared by the operation.
   * Runtime-owned authentication, tracing, proxy, framing, and cookie headers
   * are rejected before the validator is invoked.
   */
  readonly headerNames?: readonly string[];
  validate(
    input: RequestContractValidationInput
  ): MaybePromise<readonly RequestContractIssue[]>;
}

export interface RequestContractValidator {
  /**
   * Resolve an operation from routing identity only. Deliberately no query,
   * headers, body, or request object is available at this stage.
   */
  resolve(method: string, pathname: string): MaybePromise<RequestContractMatch | undefined>;
}

export interface RequestContractFailure {
  readonly status: 400 | 404;
  readonly code: "unknown_operation" | "request_contract_validation_failed";
  readonly issues: readonly RequestContractIssue[];
}

function freezePairs(
  pairs: Iterable<readonly [string, string]>
): readonly (readonly [string, string])[] {
  return Object.freeze(
    Array.from(pairs, ([key, value]) => Object.freeze([key, value] as const))
  );
}

function freezePathParams(
  values: Readonly<Record<string, string>> | undefined
): Readonly<Record<string, string>> {
  return Object.freeze({ ...(values ?? {}) });
}

function normalizeHeaderNames(
  names: readonly string[] | undefined
): readonly string[] {
  if (names === undefined) return Object.freeze([]);
  if (!Array.isArray(names)) {
    throw new TypeError("request contract headerNames must be an array");
  }

  const seen = new Set<string>();
  const normalized: string[] = [];
  for (const [index, name] of names.entries()) {
    if (typeof name !== "string" || !HTTP_HEADER_NAME_RE.test(name)) {
      throw new TypeError(
        `request contract headerNames[${index}] must be one canonical lower-case HTTP token`
      );
    }
    if (RUNTIME_OWNED_REQUEST_HEADERS.has(name)) {
      throw new TypeError(
        `request contract header ${name} is owned by authentication, tracing, proxy, or HTTP framing middleware`
      );
    }
    if (seen.has(name)) {
      throw new TypeError(`request contract header ${name} is declared more than once`);
    }
    seen.add(name);
    normalized.push(name);
  }
  return Object.freeze(normalized);
}

function projectHeaders(
  headers: Headers,
  names: readonly string[]
): readonly (readonly [string, string])[] {
  const projected: Array<readonly [string, string]> = [];
  for (const name of names) {
    const value = headers.get(name);
    if (value !== null) projected.push([name, value] as const);
  }
  return freezePairs(projected);
}

function createBodyReaders(request: Request): RequestContractBody {
  const jsonRequest = request.clone();
  const textRequest = request.clone();
  let jsonResult: Promise<unknown> | undefined;
  let textResult: Promise<string> | undefined;
  return Object.freeze({
    present: request.body !== null,
    json: () => (jsonResult ??= jsonRequest.json()),
    text: () => (textResult ??= textRequest.text())
  });
}

function normalizeIssues(
  issues: readonly RequestContractIssue[]
): readonly RequestContractIssue[] {
  if (!Array.isArray(issues)) {
    throw new TypeError("request contract validator must return an issue array");
  }
  return Object.freeze(
    issues.map((issue, index) => {
      if (
        !issue ||
        typeof issue.path !== "string" ||
        typeof issue.code !== "string" ||
        typeof issue.message !== "string"
      ) {
        throw new TypeError(`request contract issue ${index} is malformed`);
      }
      return Object.freeze({
        path: issue.path,
        code: issue.code,
        message: issue.message
      });
    })
  );
}

export async function checkRequestContract(
  validator: RequestContractValidator | undefined,
  request: Request,
  url: URL = new URL(request.url)
): Promise<RequestContractFailure | undefined> {
  if (!validator) return undefined;

  const method = request.method.toUpperCase();
  const pathname = url.pathname;
  const match = await validator.resolve(method, pathname);
  if (!match) {
    return Object.freeze({
      status: 404,
      code: "unknown_operation",
      issues: Object.freeze([
        Object.freeze({
          path: "/",
          code: "unknown_operation",
          message: "no request contract matched the HTTP method and pathname"
        })
      ])
    });
  }

  if (!match.pathTemplate.startsWith("/")) {
    throw new TypeError("request contract pathTemplate must begin with '/'");
  }

  const headerNames = normalizeHeaderNames(match.headerNames);
  const input: RequestContractValidationInput = Object.freeze({
    method,
    pathname,
    pathTemplate: match.pathTemplate,
    pathParams: freezePathParams(match.pathParams),
    query: freezePairs(url.searchParams.entries()),
    headers: projectHeaders(request.headers, headerNames),
    body: createBodyReaders(request)
  });
  const issues = normalizeIssues(await match.validate(input));
  if (issues.length === 0) return undefined;

  return Object.freeze({
    status: 400,
    code: "request_contract_validation_failed",
    issues
  });
}
