/**
 * Runtime validation boundary for schemas generated by api-docs.
 *
 * Operation selection is deliberately split from validation: `resolve` receives
 * only method + pathname. Query values, headers, and the body clone are exposed
 * only after a method/path match, so the public API cannot use them as alternate
 * dispatch selectors.
 */
export type MaybePromise<T> = T | Promise<T>;

export interface RequestContractIssue {
  readonly path: string;
  readonly code: string;
  readonly message: string;
}

export interface RequestContractValidationInput {
  readonly method: string;
  readonly pathname: string;
  readonly pathTemplate: string;
  readonly pathParams: Readonly<Record<string, string>>;
  readonly query: readonly (readonly [string, string])[];
  readonly headers: readonly (readonly [string, string])[];
  /** A clone owned by the validator; consuming it never consumes the handler request. */
  readonly request: Request;
}

export interface RequestContractMatch {
  readonly pathTemplate: string;
  readonly pathParams?: Readonly<Record<string, string>>;
  validate(
    input: RequestContractValidationInput
  ): MaybePromise<readonly RequestContractIssue[]>;
}

export interface RequestContractValidator {
  /**
   * Resolve an operation from routing identity only. Deliberately no query,
   * headers, body, or request object is available at this stage.
   */
  resolve(method: string, pathname: string): MaybePromise<RequestContractMatch | undefined>;
}

export interface RequestContractFailure {
  readonly status: 400 | 404;
  readonly code: "unknown_operation" | "request_contract_validation_failed";
  readonly issues: readonly RequestContractIssue[];
}

function freezePairs(
  pairs: Iterable<readonly [string, string]>
): readonly (readonly [string, string])[] {
  return Object.freeze(
    Array.from(pairs, ([key, value]) => Object.freeze([key, value] as const))
  );
}

function freezePathParams(
  values: Readonly<Record<string, string>> | undefined
): Readonly<Record<string, string>> {
  return Object.freeze({ ...(values ?? {}) });
}

function normalizeIssues(
  issues: readonly RequestContractIssue[]
): readonly RequestContractIssue[] {
  if (!Array.isArray(issues)) {
    throw new TypeError("request contract validator must return an issue array");
  }
  return Object.freeze(
    issues.map((issue, index) => {
      if (
        !issue ||
        typeof issue.path !== "string" ||
        typeof issue.code !== "string" ||
        typeof issue.message !== "string"
      ) {
        throw new TypeError(`request contract issue ${index} is malformed`);
      }
      return Object.freeze({
        path: issue.path,
        code: issue.code,
        message: issue.message
      });
    })
  );
}

export async function checkRequestContract(
  validator: RequestContractValidator | undefined,
  request: Request,
  url: URL = new URL(request.url)
): Promise<RequestContractFailure | undefined> {
  if (!validator) return undefined;

  const method = request.method.toUpperCase();
  const pathname = url.pathname;
  const match = await validator.resolve(method, pathname);
  if (!match) {
    return Object.freeze({
      status: 404,
      code: "unknown_operation",
      issues: Object.freeze([
        Object.freeze({
          path: "/",
          code: "unknown_operation",
          message: "no request contract matched the HTTP method and pathname"
        })
      ])
    });
  }

  if (!match.pathTemplate.startsWith("/")) {
    throw new TypeError("request contract pathTemplate must begin with '/'");
  }

  const input: RequestContractValidationInput = Object.freeze({
    method,
    pathname,
    pathTemplate: match.pathTemplate,
    pathParams: freezePathParams(match.pathParams),
    query: freezePairs(url.searchParams.entries()),
    headers: freezePairs(request.headers.entries()),
    request: request.clone()
  });
  const issues = normalizeIssues(await match.validate(input));
  if (issues.length === 0) return undefined;

  return Object.freeze({
    status: 400,
    code: "request_contract_validation_failed",
    issues
  });
}
